### ISSUE TITLE
scikit-learn instead of sklearn

### ISSUE THREAD

**Issue by Anastasis-Iliopoulos** [waico/arimafd#3]
in `arimafd.egg-info/requires.txt` and in `setup.py` scikit-learn is stated as `sklearn` but the module is installed through `scikit-learn` name.
So I think it should changed from `sklearn` to `scikit-learn` in both files.

Thank you in advance

**Comment by AbhayJha24** [comment]
Please accept my pull request, I have fixed the issue. @KozitsinSlava @YKatser @waico @Anastasis-Iliopoulos

**Comment by InSuperposition** [comment]
https://github.com/scikit-learn/sklearn-pypi-package

<img width="1570" alt="image" src="https://github.com/waico/arimafd/assets/433871/edbdc9f8-50aa-485b-b123-635703aed52b">

Please merge and release:

https://github.com/waico/arimafd/pull/4

**Comment by YKatser** [comment]
Fixed in https://github.com/waico/arimafd/pull/5
